/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface DynamicComponent {
    'props': object;
    'tag': string;
  }
  interface DynamicComponentAttributes extends StencilHTMLAttributes {
    'props'?: object;
    'tag'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'DynamicComponent': Components.DynamicComponent;
  }

  interface StencilIntrinsicElements {
    'dynamic-component': Components.DynamicComponentAttributes;
  }


  interface HTMLDynamicComponentElement extends Components.DynamicComponent, HTMLStencilElement {}
  var HTMLDynamicComponentElement: {
    prototype: HTMLDynamicComponentElement;
    new (): HTMLDynamicComponentElement;
  };

  interface HTMLElementTagNameMap {
    'dynamic-component': HTMLDynamicComponentElement
  }

  interface ElementTagNameMap {
    'dynamic-component': HTMLDynamicComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
