/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  PossibleProps,
} from './components/dynamic-component/interfaceProp';


export namespace Components {

  interface DynamicComponent {
    'props': PossibleProps;
    'tag': string;
  }
  interface DynamicComponentAttributes extends StencilHTMLAttributes {
    'onUpdateComp'?: (event: CustomEvent) => void;
    'props'?: PossibleProps;
    'tag'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'DynamicComponent': Components.DynamicComponent;
  }

  interface StencilIntrinsicElements {
    'dynamic-component': Components.DynamicComponentAttributes;
  }


  interface HTMLDynamicComponentElement extends Components.DynamicComponent, HTMLStencilElement {}
  var HTMLDynamicComponentElement: {
    prototype: HTMLDynamicComponentElement;
    new (): HTMLDynamicComponentElement;
  };

  interface HTMLElementTagNameMap {
    'dynamic-component': HTMLDynamicComponentElement
  }

  interface ElementTagNameMap {
    'dynamic-component': HTMLDynamicComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
